compressionLevel: mixed
enableGlobalCache: false
nodeLinker: node-modules
supportedArchitectures:
  os: [linux, darwin, win32]
  cpu: [x64, arm64]
  libc: [glibc, musl]

plugins:
  - checksum: 4ae37aa0a6a0d226889f66fb2f7482e321b0c82b8fa8ed2110d8cdfbd482c87542050ded54cb08bf473e4245ef0160668c689c93848416499a975d876a1e18b1
    path: .yarn/plugins/yarn-plugin-nixify.cjs
    spec: "https://github.com/stephank/yarn-plugin-nixify/raw/85edd52bc260755131e98736aa5588429d275d6a/dist/yarn-plugin-nixify.js"

# yarn-plugin-nixify options
generateDefaultNix: false
nixExprPath: nix/yarn-project.nix
