compressionLevel: mixed
nodeLinker: pnp
supportedArchitectures:
  os: [linux, darwin, win32]
  cpu: [x64, arm64]
  libc: [glibc, musl]

packageExtensions:
  "@storybook/core-common@*":
    dependencies:
      "@storybook/react-vite": "^7"
      "react-dom": "^18"
      "vite": "^4"
  "@storybook/builder-vite@*":
    dependencies:
      "vite": "^4"
  "@vitejs/plugin-react@*":
    dependencies:
      "vite": "^4"

plugins:
  - checksum: 4ae37aa0a6a0d226889f66fb2f7482e321b0c82b8fa8ed2110d8cdfbd482c87542050ded54cb08bf473e4245ef0160668c689c93848416499a975d876a1e18b1
    path: .yarn/plugins/yarn-plugin-nixify.cjs
    spec: "https://github.com/stephank/yarn-plugin-nixify/raw/85edd52bc260755131e98736aa5588429d275d6a/dist/yarn-plugin-nixify.js"

# yarn-plugin-nixify options
generateDefaultNix: false
nixExprPath: nix/yarn-project.nix
