enableConstraintsChecks: true

generateDefaultNix: false

nixExprPath: nix/yarn-project.nix

nodeLinker: node-modules

packageExtensions:
  "@storybook/builder-vite@*":
    dependencies:
      vite: ^4
  "@storybook/core-common@*":
    dependencies:
      "@storybook/react-vite": ^7
      react-dom: ^18
      vite: ^4
  "@vitejs/plugin-react@*":
    dependencies:
      vite: ^4

plugins:
  - checksum: 262555f70f393385c7b94658bf64e3c673a90cb79b6e3da036c5ff89e2b0133a033c620632b88e1252356926322922deb809aee91bb1c6d1ce0f2d8a4c917480
    path: .yarn/plugins/yarn-plugin-nixify.cjs
    spec: "https://github.com/stephank/yarn-plugin-nixify/raw/649a8a80988040093dbeca4eb79fcb04715cc843/dist/yarn-plugin-nixify.js"

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - linux
    - darwin
    - win32
