compressionLevel: mixed
enableGlobalCache: false
nodeLinker: node-modules
supportedArchitectures:
  os: [linux, darwin, win32]
  cpu: [x64, arm64]

plugins:
  - path: .yarn/plugins/plugin-list.cjs
    spec: "https://github.com/arendjr/yarn-plugin-list/releases/latest/download/yarn-plugin-list.js"
  - checksum: 4ae37aa0a6a0d226889f66fb2f7482e321b0c82b8fa8ed2110d8cdfbd482c87542050ded54cb08bf473e4245ef0160668c689c93848416499a975d876a1e18b1
    path: .yarn/plugins/yarn-plugin-nixify.cjs
    spec: "https://raw.githubusercontent.com/stephank/yarn-plugin-nixify/main/dist/yarn-plugin-nixify.js"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
