packages:
  - packages/*
catalog:
  "@catppuccin/palette": ^1.7.1
  "@tsconfig/node20": ^20.1.4
  "@types/node": ^20.17.25
  "@vscode/vsce": ^3.3.0
  "eslint": ^8.57.1
  "tsup": ^8.4.0
  "tsx": ^4.19.3
  "typescript": ^5.8.2
onlyBuiltDependencies:
  - "@vscode/vsce-sign"
  - esbuild
ignoredBuiltDependencies:
  - keytar
