packages:
  - packages/*

catalog:
  '@catppuccin/palette': ^1.7.1
  '@tsconfig/node22': ^22.0.5
  '@types/node': ^24.0.0
  '@vscode/vsce': ^3.7.0
  eslint: ^9.39.1
  tsup: ^8.5.1
  tsx: ^4.20.6
  typescript: ^5.9.3

ignoredBuiltDependencies:
  - keytar

onlyBuiltDependencies:
  - '@vscode/vsce-sign'
  - esbuild
