packages:
  - packages/*

catalog:
  '@catppuccin/palette': ^1.7.1
  '@tsconfig/node22': ^22.0.2
  '@types/node': ^22.18.0
  '@vscode/vsce': ^3.6.0
  eslint: ^9.34.0
  tsup: ^8.5.0
  tsx: ^4.20.5
  typescript: ^5.9.2

ignoredBuiltDependencies:
  - keytar

onlyBuiltDependencies:
  - '@vscode/vsce-sign'
  - esbuild
